name: Build GSM Mert Tweak

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git perl libssl-dev libyaml-dev make wget curl unzip clang lld llvm

      - name: Install Theos & SDK
        run: |
          git clone --recursive https://github.com/theos/theos.git /opt/theos
          curl -LO https://github.com/theos/sdks/archive/refs/heads/master.zip
          unzip master.zip
          mv sdks-master/iPhoneOS14.5.sdk /opt/theos/sdks/
          rm -rf master.zip sdks-master

      - name: Create Complete Linux Toolchain Links
        run: |
          sudo chmod -R 777 /opt/theos
          # Theos'un aradığı Linux toolchain dizinini eksiksiz oluşturuyoruz
          sudo mkdir -p /opt/theos/toolchain/linux/iphone/bin
          
          # Sistemdeki tüm derleme araçlarını Theos'un beklediği konuma bağlıyoruz
          sudo ln -sf /usr/bin/clang /opt/theos/toolchain/linux/iphone/bin/clang
          sudo ln -sf /usr/bin/clang++ /opt/theos/toolchain/linux/iphone/bin/clang++
          sudo ln -sf /usr/bin/llvm-ar /opt/theos/toolchain/linux/iphone/bin/ar
          sudo ln -sf /usr/bin/llvm-strip /opt/theos/toolchain/linux/iphone/bin/strip
          sudo ln -sf /usr/bin/lld /opt/theos/toolchain/linux/iphone/bin/ld

      - name: Build Tweak (.deb)
        run: |
          cd $GITHUB_WORKSPACE
          export THEOS=/opt/theos
          make package FINALPACKAGE=1

      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GSMRelayOutgoing-deb
          path: packages/*.deb
